# Generated by Django 5.0.1 on 2024-01-21 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hunt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Treasure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('description', models.CharField()),
                ('point_value', models.IntegerField()),
                ('limit', models.IntegerField(default=1)),
                ('hunt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scavanger.hunt')),
            ],
        ),
    ]
